spring.application.name=rest-api-many-to-many-example

#Configurar las credenciales de conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/many-to-many-mostoles-backend-2026
spring.datasource.username=root
spring.datasource.password=Temp2025

# Para configurar el ORM Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# La siguiente clave (key) ofrece mas informacion por la consola respecto a las consultas
# o sentencias del SQL generadas por HIBERNATE
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.deserialization.fail-on-null-for-primitives=false
